### ISSUE TITLE
ROP search is not very good.

### ISSUE THREAD

**Issue by crowell** [radareorg/ideas#11]
#  Things that rop needs
- [ ] auto ropper (not soon)
- [ ] primitive detecting (pivot, leak, write-what-where, etc.) 
- [x] start at "end" gadgets and disassemble backwards (for speed) (pr radareorg/radare2#1835 )
- [x] regexp search (pr radareorg/radare2#1679 )
- [x] not search nx pages (_only_ search in executable pages)
- [x] remove the comma as a delimiter (perhaps use / as delimiter?) (pr radareorg/radare2#1722 semicolon delimeter)
- [x] cache the results in sdb
