### ISSUE TITLE
META - Make esil as accurate as debugging

### ISSUE THREAD

**Issue by oddcoder** [radareorg/ideas#119]
This issue is to fix most bugs with esil and make is as close to debugging as possible
I will add more issues here once I encounter them
- [ ] Increase stack size for esil, I saw some binaries that overflow esil stack (unfortunately I dont have them any more)
- [ ] One another things is how interrupts are emulated (for example `int 3`).
- [ ]  what about something like `lea eax, ebp, jmp eax` then when I check memory at ebp in r2 I find it zeroed out.
- [ ] System calls too needs to be emulated.
- [ ] something like this

```
call sym.imp.malloc
cmp eax, 0
je exit:
.
.
.
.
exit: call sym.imp.exit
```

should we have some sort of symbolic execusion to initialize registers and memory to always take the longest path in code ? (similar to https://github.com/radare/radare2/issues/4722)
