### ISSUE TITLE
META - Rahash2

### ISSUE THREAD

**Issue by Maijin** [radareorg/ideas#152]
# META - RAHASH2

* [ ] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/blob/master/t.tools/rahash2/rahash2
* Command - `woD, woE, rahash2 -E, rahash2 -D, pr?`
* [ ] BlogPost - TBD
* .c involved:
    * https://github.com/radare/radare2/tree/master/libr/crypto
    * https://github.com/radare/radare2/tree/master/libr/hash
    * https://github.com/radare/radare2/blob/master/binr/rahash2/rahash2.c
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_write.c#L316-L317

### Hashes

* [ ] Implement [Blake2](https://tools.ietf.org/html/rfc7693)
* [ ] Implement [murmur hash](https://github.com/salviati/slash/blob/master/hash.cc)
* [ ] Implement [Locality-sensitive hashing](https://en.wikipedia.org/wiki/Locality-sensitive_hashing)
* [ ] Implement hsalsa20 [[1]](https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/HSalsa20.c) [[2]](https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/test-salsa.c)

### Crypto

- [ ] ChaCha20
- [ ] 3DES
- [ ] [SPECK](https://en.wikipedia.org/wiki/Speck_(cipher))
- [ ] [XTEA](https://github.com/Varbin/xtea)
- [ ] Serpent CBC
- [x] Serpent ECB

### Decoders

* [ ] Add [custom alphabets](https://www.malwaretracker.com/decoder_base64.php) for woE woD baseXX using the key
`rahash2 -D base64 -S "ZYXW... -s "YWRtaW4="` 

### Compressions Algorithms
Add the Compressions Algorithm in rahash2, `woD`, `woE`, `pr?` and `wtf`.

* [ ] zip
* [ ] lzma
* [ ] lz4
* [ ] lznt1
* [ ] aPlib
* [ ] lzmat
* [ ] deflate
* [ ] lzfse
* [x] gzip
