### ISSUE TITLE
META - Ragg2

### ISSUE THREAD

**Issue by Maijin** [radareorg/ideas#153]
# META - Ragg2

* [ ] Book https://github.com/radare/radare2book/issues/216
* Tests : https://github.com/radare/radare2-regressions/tree/master/t.tools/ragg2
* Commands : `g, ragg2`
* [ ] BlogPost : TBD 
* .c involved:
    * https://github.com/radare/radare2/tree/master/binr/ragg2

## Fixes

* [x] ragg2 encoding is not working https://github.com/radare/radare2/issues/1267
* [x] Multiple strings in ragg2 egg files doesn't work https://github.com/radare/radare2/issues/3235

## Enhancements

* [x] Use [MPC](https://github.com/orangeduck/mpc) for Ragg2 parsing, much better than doing our own syntax parser or bison/yacc
* [ ] Support ragg2 with sys/ndk-gcc 
* [ ] Support ragg2 in Termux
* [ ] ragg2 - link with SSP for hardened systems radareorg/radare2#8976 
* [ ] Add Export in De Brujin Graph using DNA radareorg/ideas#78

## New architectures

* [ ] ARM64
* [ ] MIPS
* [ ] PowerPC
* [ ] SPARC
* [ ] AVR
* [ ] RISC-V
