### ISSUE TITLE
META - ROP

### ISSUE THREAD

**Issue by Maijin** [radareorg/ideas#154]
# Related

* [ ] Doc : TBD
* Tests : https://github.com/radare/radare2-regressions/blob/master/t/cmd_rop
* Command : `/R`
* [ ] BlogPost : http://radare.today/posts/ropnroll/
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_search_rop.c

# Enhancement

* [ ] Rop gadget classification
Classify them in those categories (See merged PR here - radareorg/radare2#5448 radareorg/radare2#5481 radareorg/radare2#5515 radareorg/radare2#5531 )
    * [ ] NOP                         
    * [ ] JUMP            EIP = AddrReg + Offset
    * [ ] MoveReg         OutReg = InReg
    * [ ] LoadConst       OutReg = Value
    * [ ] Arithmetic      OutReg = InReg1 <op> InReg2
    * [ ] LoadMem         OutReg = [AddrReg + Offset]
    * [ ] StoreMem        [AddrReg + Offset] = InReg
    * [ ] ArithmeticLoad      OutReg = OutReg <op> [AddrReg + Offset]
    * [ ] ArithmeticStore     [AddrReg + Offset] = [AddrReg + Offset] <op> InReg

* [ ] Enhance SDB ROP storage - https://github.com/radare/radare2/issues/5162
* [ ] Rop search improvement - https://github.com/radare/radare2/issues/4284
* [ ] ROP Search using ESIL - https://github.com/radare/radare2/issues/2612
* [ ] Auto ropper https://github.com/radare/radare2/issues/1708
* [ ] Primitive detecting (pivot, leak, write-what-where, etc.) https://github.com/radare/radare2/issues/1708

### Building a complete ROPChain

- [ ] Identify gadget semantically (likely with ESIL)
  - [ ] move a register `A` into a _register_ `B`
  - [ ] move a register `A` into an _offset_ `B`
  - [ ] syscall
  - [ ] set a _register_ `A` to zero
  - [ ] increment a _register_ `A`
- [ ] Borrow code from RopGadget to generate the ropchain.
#### Sources
- [mona.py](https://www.corelan.be/index.php/2011/07/03/universal-depaslr-bypass-with-msvcr71-dll-and-mona-py/)
- [ROPGadget](https://github.com/JonathanSalwan/ROPgadget/)
