### ISSUE TITLE
META - UTF-8 and BiDi support for the various languages

### ISSUE THREAD

**Issue by XVilka** [radareorg/ideas#19]
- [x] Support in the comments (including the ascii graph mode https://github.com/radare/radare2/issues/1098, https://github.com/radare/radare2/issues/1675, https://github.com/radare/radare2/issues/1566)
- [x] Store the flags space and flag names in the SDB https://github.com/radare/radare2/issues/2389
- [x] Fix glitches in visual mode https://github.com/radare/radare2/issues/2359
- [x] Printing Unicode strings (including another formats (UTF-16, UTF-32, etc) https://github.com/radare/radare2/issues/926
- [x] Support in the panels https://asciinema.org/a/17305
- [x] V! panels and Unicode (UTF-8)
- [x] Unicode compatibility on Windows https://github.com/radare/radare2/issues/7235
- [x] `p=` commands and Unicode (UTF-8) https://github.com/radare/radare2/issues/14351
- [x] `p-` commands and Unicode (UTF-8) https://github.com/radare/radare2/issues/14352
- [ ] Support in the strings operation (including the search operations)
- [ ] String references with emojis shown in disasm
- [ ] Support for the various code pages esp. code page 437, windows-1252, iso 8859-5?
- [ ] Support for right-to-left scripts e.g. Arabic, Hebrew, Persian ... with/without console support
- [ ] Support for character shaping e.g. for Arabic, Persian ... with/without console support
- [ ] Support for combining characters e.g. diacritics esp. in graph mode
- [ ] Graceful fallback for error cases esp. in graph mode
