### ISSUE TITLE
META - SystemZ and z/OS support

### ISSUE THREAD

**Issue by bigendiansmalls** [radareorg/ideas#55]
# Overview

Missing features for the architecture and platform:
- [ ] Opcodes analysis, including stack analysis
- [ ] Opcodes uplifting to ESIL
- [ ] ESIL profile for emulation
- [ ] Support to be compiled and ran on z/OS platform
- [ ] Support native debugging on z/OS platform
- [ ] Support to be able to connect to remote GDB server running on z/OS platform
- [ ] EBCDIC character set support  https://github.com/radareorg/radare2/issues/16513

# Capstone

The following Capstone issues should be fixed:
- https://github.com/aquynh/capstone/issues/1545
- https://github.com/aquynh/capstone/issues/1576
- https://github.com/aquynh/capstone/issues/1546

# More information

Here are some documents / binaries which define or represent the platform.   

This is the principles of operations manual - it documents the architecture, memory, CPU and all the machine-level (assembly) instructions, opcodes and formats.

https://goo.gl/AkE07w

I've many examples of system z assembly programs written on my blog:

https://www.bigendiansmalls.com

Here is an example of a binary compiled on the system (debugging symbols enabled).

https://goo.gl/caSnRt

And the source code /assembly listing for that binary.

https://github.com/bigendiansmalls/misc_z_code/blob/master/hello_world.c
https://github.com/bigendiansmalls/misc_z_code/blob/master/hello_world.txt

Initially trying to get all the opcodes / listings (ch 7-10) out of the Principles of ops manual into a usable format.

For example from page 7-43 (Branch Relative and Save) (BRAS)
![image](https://cloud.githubusercontent.com/assets/13771080/10282654/97eea8c4-6b41-11e5-80a9-16fc2daf29d9.png)

Would be useful to have a grepable text (or xml/json) file that could be manipulated then for header files in various places (capstone,  r2, etc)  such as (i made this one up, but others would work too)

**`bras,[RI-b],32,{'A7',{R1:4},{'5':4},{RI2:16}}`**
where
instruction_name,[instruction format],total_length,{'constant':length,[{'constant':len}|{field_name:len}...}

Then that file can be easily used to build other header files and such.

**Comment by XVilka** [comment]
The issue is still valid as always, but we can't do anything until capstone updates the support.
