### ISSUE TITLE
[TRACKER] radare2 is not cool as mona.py

### ISSUE THREAD

**Issue by jvoisin** [radareorg/ideas#7]
[mona.py](https://www.corelan.be/index.php/2011/07/14/mona-py-the-manual/) is a handy python script from [corelan](http://corelan.be), designed to assist in exploits development. I don't know how much do we want r2 to be designed for this purpose, but I think that we should _borrow_ some of their features:
- [ ] Building a [complete ROP chain](https://github.com/radare/radare2/issues/1131)
- [ ] [Badchar detection](http://www.youtube.com/watch?v=-D2QQYuneu8)
- [ ] Jump to reg: search for pointers that will lead to execute the code located at the address pointed by a given register. 
- [ ] Searching for specialized gadgets such as for SEH overwrite, stackpivots.
- [ ] Showing all loaded modules with all their security features.
- [ ] Find pattern in memory (marking if it's in SEH, sEIP or registers)
- [x] [Heap visualization](https://www.corelan.be/index.php/2013/01/18/heap-layout-visualization-with-mona-py-and-windbg/).
- [x] Display memory map (`dm`). This could be improved (ASLR/...)
- [x] Assemble/disassemble.
- [x] Search instructions/strings/...
- [x] [Cyclic patterns](https://github.com/radare/radare2/issues/900) 
- [x] Search with wild-cards (like `!mona findwild -s "push r32#*#pop eax#inc eax#*#retn"`)
- [x] [Analyse](https://www.corelan.be/index.php/2014/08/16/analyzing-heap-objects-with-mona-py/) the heap, especially guessing pointers.
