### ISSUE TITLE
META - Rabin2

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#91]
# Related

* DOC: TBD
* BLOG: TBD
* Tests : https://github.com/radare/radare2-regressions/blob/master/t.tools/rabin2/rabin2
* .c involved:
    * https://github.com/radare/radare2/tree/master/binr/rabin2

# Fixes

# Enhancements

* [ ] rabin2 -l should check for unexistent libs in system like ldd
* [ ] Support iOS OTA unpacker (Like in rabin2 -x or maybe just directly in r_fs plugin) - http://newosxbook.com/src.jl?tree=listings&file=ota.c
* [ ] Add support for mangling symbols (reverse of rabin2 -D)
* [ ] Add rabin2 -k to handle OpenBSD for rabin2 -C radareorg/radare2#6396

### Simplify header information

This how we should just reuse what's in r2 -nn to extract the prettyprinted form .. so imho the iH should be implemented using this to avoid duplicating the parser

```
[0x00000000]> pf.mach0_header
      magic : 0x00000000 = 0xfeedfacf
    cputype : 0x00000004 = 0x01000007
...
[0x00000000]> pf*mach0_header
f magic=0x00000000
f cputype=0x00000004
f cpusubtype=0x00000008
...
```

### Add classes (rabin2 -c)

* [ ] MZ (msdos friendly)
* [ ] PE64 (32bit is supported, not 64)
* [ ] MACH0-PowerPC (i think arm/x86 is covered already)
* [ ] more...

### Add more fileformats

* [ ] MACH0 (output similar to otool -l)
* [ ] ELF (output similar to readelf)
* [ ] PE (output similar to pestudio or pf.X)

## FAT

* [ ] rabin2 -x should not work on non-fat binaries
* [ ] PoC rabin2 -x use pointers instead of sdb

## Rabin2 -O operations

- [ ] Fix checksum for given file ("done" for DEX, but must be available for others)
- [ ] ldid (sha256 "sign" iOS binaries) (rabin2 -O ldid is documented and works, but only to show the current entitlements. it is not able to change them (yet))
- [ ] Change executable interpreter
- [ ] Remove section
- [ ] rabin2 -O unfair - remove cryptid/off from mach0 binaries
- [ ] rabin2 -O should obey -r and show r2 commands instead of binpatching
